#+TITLE: On Java

There were object oriented languages before Java, and there have been object oriented languages since Java. But I think
we can all agree that, in the minds of the public (certainly within education), the role of the "OOP holotype" has been
abstorted by Sun Microsystems' little anti-christ. Sorry, Alan.

I do not like Java.

It is not my /most/ hated language -- by a long shot -- but it has one of the highest
problems-I-have-with-it-to-TIOBE-popularity ratios. Java is /brutally/ single-minded in its drive to solve problems
*backwards.* Where other languages structure programs as collections of things and things to do, Java enforces a model
where all programs are structured as lists of things to do stuff to. Where other languages provide more ways to pattern
data than I can count, Java provides only ~Objects~ (and a /bare/ minimum of primitives), which it has to cram into the
mold of other, more proper types. Where other languages give developers the means to organize code into files, Java
gives developers the means to organize files into code. Where other languages offer a variety of application packaging
solutions (even other bytecode ecosystems, like CLI), Java enforces a wholly unique "lazy dynamic linking" scheme that
obliterates security[fn:1], compatibility, VM portability, other people's libraries, and its own standard library
(~javax~ lmao); all for no /actual/ benefit to programmers.

Why? Because Java is not a high-level language. It is not interested in making it easy to write good programs, it is
interested in making it easy to write ~.class~ files. Or, rather, easy for ~javac~ to /produce/ ~.class~ files, and for
the JVM to /comprehend/ ~.class~ files. Ever read chapter 4 of the JVM spec[fn:2], or poked around with ~javap~? Or even
just tried a Java decompiler? It's immediately obvious that ~.class~ files are not a serious object[fn:3] format.
They're a serialization scheme for Java source code, that happens to translate method implementations into stack machine
instructions.

Want to mix code and data without classes? No can do, we're here to serialize class files. Want to put two top-level
classes in one file? No can do, we want a 1:1 mapping between source files and bytecode files. Want code inlining? No
can do, we're not a compiler. Want generics? Sorry, not in the schema, but we /do/ have type erasure. Is that what you
wanted? Want inheritance? We've got that actually, because the superclass relationship is encoded in the ~.class~ file.
There's a little field, right there in the header, where you stick a UTF-8 string with the name of your superclass.
(Actually: it's a reference to a UTF-8 string in the /constant pool,/ but I digress.) Inheritance is compulsory, it's
/structurally impossible/ to opt out of.

Consider record classes, for example: what do they provide the programmer? Default implementations of
~toString:()Ljava/lang/String;~, ~hashCode:()I~, and ~equals:(Ljava/lang/Object;)Z~, some automatic access flags, some
getter methods -- in other words: things we could already write by hand (or IDE auto-complete) and things ~javac~ could
already emit, but now that they're codified, it's easier to reason about.

That's why Oracle, upon deciding to introduce records for Java 14, Oracle decided that they should require brand-new
hardcoded information in their headers. What's the point in a new language feature if we don't make it
backwards-incompatible? That's not befitting of a serialization scheme!

By insisting on this inabstract[fn:4] coupling between language version and class file version (neither may contain any
more or less information than the other, no exceptions!) we necessarily also couple language version to /JVM version/,
and thus also /JRE/ version, and thus also your /dependencies'/ versions. We've managed to invent a compiled language
that requires polyfills for /syntax sugar!/

Want vararg methods? They're encoded with special facilities in the class file, force a minimum language version, a
minimum target version, and minimum dependency versions. Want generics or bridge methods? They're encoded with special
facilities in the class file, force a minimum language version, a minimum target version, and minimum dependency
versions. Want enums? They're encoded with special facilities in the class file, force a minimum language version, a
minimum target version, and minimum dependency versions. Ditto dynamic method calls (read: closures), annotations, inner
classes, records (as we discussed), modules, and the entirety of the standard library. Among other things. Perhaps
within a generation or two we'll see a class attribute that stores its author's social security number...

So, what exactly do we /gain/ from gritting our teeth, eschewing our ivory tower ideals like "use the right tool for the
job", "you should probably know the type of your variables" or "splitting a single procedure across thirty files is
confusing", and obliterating our programs into the ten thousand little self-contained macro-assembler DLLs that ~javac~
expects?

Nothing. We gain nothing!

Project structure? Don't make me laugh.

Portability? Runtime polymorphism? Dependency injection? Instrumentation? Done better by better languages.

Reflection? Exceptions? Aspect-oriented programming? Runtime inheritance? Come on. Done better by better languages,
/and/ anti-patterns -- inheritance in particular. ~Dog~ extends ~Animal~ is all well and good, James, but it turns out
that we need to model our application, too. ~Dog~ extends ~Animal~ extends ~AbstractLivingThingBean~ which implements
~java.io.Serializable~ and extends ~java.awt.Canvas~ which implements ~java.awt.iamge.ImageObserver~ and
~java.awt.MenuContainer~ and ~java.io.Serializable~ and ~javax.accessibility.Accessible~ and extends
~java.awt.Component~ which implements ~java.awt.iamge.ImageObserver~ and ~java.awt.MenuContainer~ and
~java.io.Serializable~ and extends ~java.lang.Object~? I think even the evangelists have admitted this doesn't work.

Even ~.class~ files themselves have been done better by better languages! Kotlin, Scala, Groovy, Clojure -- turns out
developers want to be able to translate the high-level things they write into a portable low-level representation,
rather than just write portable low-level representations (but with words instead of numbers). Who knew?

I'll /use/ Java, of course. If demanded. There are worse things to be single-minded about than classes. The Eclipse LSP
goes a long way to make complicated ideas easier to express.

But you'll never see me advocate for Java. Especially not within education, especially not for starting new projects,
especially not if interop with another JVM language is an option. /Please/ use something which respects that your needs
are different from ~javac~'s needs.
* Footnotes
[fn:1] I'll fucking "illegal reflective access" your /dick/, how about that? While the ~ProtectionManager~ watches? Gonna
warn me about THAT? Gonna go running to the maintainers of ~javassist.util.proxy.SecurityActions~? Gonna deny it in a
future release?

...sorry.

[fn:2] https://docs.oracle.com/javase/specs/jvms/se25/html/jvms-4.html

[fn:3] As in an https://en.wikipedia.org/wiki/Object_file, not the OOP meaning of "object". (Or, for that matter, any
OOP notions of "persistent objects".)

[fn:4] I mean the prefix "in-" here in the sense of "lacking" or "without". "Inabstract" = "Lacking abstraction".
Wiktionary can me all it wants that this is "not a real word", Google books has a whole /several/ hits for "inabstract"
-- at least *four* of them aren't even OCR errors! We've got one paper from 1975, two English translations from Latin
texts, and a no-name dictionary from 1861 that lists "inabstracted" and I /think/ implies "inabstract" as well. (It
would be omitted to save space, the poor guy already had to chop out parts of his introduction just to cram it into a
thousand pages) There's also an entry for "inabstracted" (but not "inabstract") in the online version of the 1913
Webster's Dictionary.
