#+SETUPFILE: ./common/common.org
{{{extra_config}}}
#+TITLE: My Wabsite
#+OPTIONS: toc:2
* Introduction

** Introduction Introduction Introduction
Hi! Welcome to my ~#webpresence~. Mostly just GitHub pages-squatting over here.

Figured I'd like somewhere to dump whatever I couldn't get to work as a regular Tumblr post. Maybe I'll eventually grow
my ambitions, maybe I won't.

You can find me most other places under the username "metroidisprettycool", "metroidipc", "mipc", or some variation
thereof.

It's unprofessional, clearly, but I made my first real "social media" account (Reddit, since deleted) under that name,
and I value consistency more than I value being professional.

#+begin_aside
Also, /Metroid/ *is* pretty cool. Ever try /Metroid Prime/? \\
*Man.* That's a good game.
#+end_aside

** What's Your Deal?
[[file:lists/00-taking-sides.org][Here's a collation of all my stances on the usual trivial debates.]]

I tend to pendulum around between "computer nerd stuff", "aerospace nerd stuff", and watching lots of movies while I
fantasize about bombing the Map-Territory distinction. Loops and recursion and self-similarity fascinate me. Y'know,
turbonerd stuff.

** Whatcha Make?
[[file:lists/10-programming-projects.org][Here's a list of some of the big(ish) hobby programming projects I've done,
and my post-mortem thoughts on each.]]

* Sub-Indices

** Writing
- [[file:essays/index.org][Essays]] :: Long-form opinions on various topics.

- [[file:lists/index.org][Lists]] :: Lists of several kinds, mix of fact and opinion, all entries otherwise too short
  for something more dedicated.

- [[file:guides/index.org][Guides]] :: Guides for how do things, representing my own original research.

* XHTML? In 2025?
Pretty good gag, right? =:P=

\\

I have no particular love for XML, it is an embarrassing format. Does anything else epitomize that /slavish/ 90s
devotion to bureaucracy quite like DTDs?

But I had to pick /something,/ and HTML is just apocalyptic.

The Org mode[fn:3] team seems to concur with my sentiment, given that XHML 1.0-strict is its default doctype for HTML
export; so that's what I started with. /Unfortunately/ -- despite proudly embedding a W3C Validtor link at the bottom of
every page -- they're /also/ content to do things like spew out style tags in ~<body>~, hardcode DPUB-ARIA attributes
without the right doctype,[fn:4] and emit all sorts of illegal entities without exposing the configuration options to
fix it.

After a bit of work, I found that the XHTML5 doctype, paired with a post-publishing ~tidy~[fn:5] hook, seemed to clean
up best. So that's what I stuck with.

Will I /continue/ to stick with it? I dunno. The strictness is pretty helpful for scripting some na\iuml​ve document
transformations, like link-rewriting, so I probably won't switch to plain HTML. Maybe I'll try to put together an XHMTL
1.0 + WAI-ARIA 1.0 + IFrames DTD at some point, as a bit of experimental archaeology? Or maybe I won't. This whole
ordeal has given me a pretty dim view of document formatting in general -- $\LaTeX$, you're also part of the problem --
so maybe I'll just go back to hunting mammoths and living in caves instead. Probably a more satisfying lifestyle...

* {{{license_footer(2025)}}}

* Footnotes

[fn:3] [[https://orgmode.org/]]

[fn:4] Prioritizing accessibility is admirable, don't get me wrong, but I don't understand why you wouldn't just use
[[https://www.w3.org/WAI/ARIA/Schemata/xhtml-aria-1.dtd]]? Or at /least/ bring in the standalone module? \\

\\

Sure, they aren't recommended by W3C for real documents; but they /also/ haven't been touched since 2010, and the DTD
traffic problem isn't exactly pertinent anymore. (Moreover: if you cared so much, you could also host them yourself!)

[fn:5] [[https://www.html-tidy.org/]]
