#+SETUPFILE: ./common/common.org
{{{extra_config}}}
#+TITLE: My Wabsite
#+OPTIONS: toc:2
* Introduction

** Introduction Introduction Introduction
Hi! Welcome to my ~#webpresence~.

Figured I'd like somewhere to dump whatever I couldn't get to work as a regular Tumblr post. Maybe I'll eventually grow
my ambitions, maybe I won't.

You can find me most other places under the username "metroidisprettycool", "metroidipc", "mipc", or some variation
thereof.

It's unprofessional, clearly, but I made my first real "social media" account (Reddit, since deleted) under that name,
and I value consistency more than I value being professional.

#+begin_aside
Also, /Metroid/ *is* pretty cool. Ever try /Metroid Prime/? \\
*Man.* That is a good game.
#+end_aside

** What's Your Deal?
[[file:lists/00-taking-sides.org][Here's a collation of all my stances on the usual trivial debates.]]

I tend to pendulum around between "computer nerd stuff", "aerospace nerd stuff", and watching lots of movies while I
fantasize about bombing the Map-Territory distinction. Loops and recursion and self-similarity fascinate me. Y'know,
turbonerd stuff.

** Whatcha Make?
[[file:lists/10-programming-projects.org][Here's a list of some of the big(ish) hobby programming projects I've done,
and my post-mortem thoughts on each.]]

* Sub-Indices

** Writing
- [[file:essays/index.org][Essays]] :: Long-form opinions on various topics.

- [[file:lists/index.org][Lists]] :: Lists of several kinds, mix of fact and opinion, all entries otherwise too short
  for something more dedicated.

- [[file:guides/index.org][Guides]] :: Guides for how do things, representing my own original research.

* XHTML? In 2025?
Pretty good gag, right? =:P=

I'm not doing it for compatibility with old browsers (I'm totally fine with using ~&~ selectors in my CSS, for example)
and I'm not doing it out of any love for XML (it's an embarrassing format). My reasoning here is totally nontechnical, I
just like playing with touys.

1. HTML is even more embarrassing than XML is, and I want to take whatever tiny stand I can against it.

2. Org mode[fn:1] automatically inserts a link to the W3C Markup Validator at the bottom of the page, and (after a bit
   of work from me, like writing a post-publishing ~tidy~[fn:2] hook) XHTML5 was the easiest to get to /pass/ that
   validation.[fn:3]

3. I like dumpster diving through the annals of technical history to get a better idea of why and how we got here.

4. XHTML being so strict makes it substantially easier for me to na\iuml​vely script some basic transformations in my
   export pipeline.

So going mainstream with HTML5 is never gonna happen, it doesn't meet any of those criteria. A manually assembled XHTML
1.1 + WAI-ARIA 1.0 + IFrames DTD is on the table, though, as a bit of experimental archaeology. Or maybe I'll go even
further back! HTML 3.2, anyone? 2.0? [[file:./other/htmlplus.html][HTML+]]? I /will/ do it if pushed, don't test me!

* {{{license_footer(2025)}}}

* Footnotes

[fn:1] [[https://orgmode.org/]]

[fn:2] [[https://www.html-tidy.org/]]

[fn:3] The default Org mode export doctype, interestingly, is actually /XHTML 1.0-strict./ Boggles the mind they would
pair /that/ with the validator link being on by default, when there's so much hardcoded invalid behavior for that
doctype. Style tags in ~<body>~, DPUB-ARIA attributes without the right doctype, all sorts of illegal entities without
exposing the configuration options to fix it, etc.
\\
The ARIA is particularly silly. Prioritizing accessibility is admirable, don't get me wrong, but I don't understand why
you wouldn't just use [[https://www.w3.org/WAI/ARIA/Schemata/xhtml-aria-1.dtd]] if you're going to bring them in? Or at
/least/ bring in the standalone module?
\\
Sure, they aren't recommended by W3C for real documents; but they /also/ haven't been touched since 2010, and the DTD
traffic problem isn't exactly pertinent anymore. (Moreover: if you cared so much, you could also host them yourself!)
