#+TITLE: My Wabsite
#+OPTIONS: toc:nil
#+TOC: headlines 2
* Introduction
** Introduction Introduction Introduction
Hi! Welcome to my ~#webpresence~.

There's not much here, which is sort of deliberate. Just wanted to replace the nonsense that was here previously with
something that isn't /obviously unfinished./ Maybe I'll expand later, maybe I won't. At the moment I have no current
plans to do besides GitHub Pages-squat.

You can find me most places under the username "metroidisprettycool", "metroidipc", "mipc", or some variation thereof.
It's unprofessional, clearly, but I made my first real "social media" account (Reddit, since deleted) under that name
and I value consistency more than I value being professional.
** What's Your Deal?
[[file:lists/00-taking-sides.org][Here's a collation of all my stances on the usual trivial debates.]]

I tend to pendulum around between "computer nerd stuff", "aerospace nerd stuff", and watching lots of movies while I
fantasize about bombing the Map-Territory distinction.

As a computer nerd, I like most of the usual computer nerd things. Programming, maintaining my franken-Arch Linux
installation, arguing, video games, PC-building, arguing, reading Douglas Hofstadter books and stroking my chin very
thoughtful-like,[fn:2] arguing...

As a space nerd, I have a big soft spot for the space shuttle. So, very, very, very flawed. But at that time, under
those governments, knowing then only what we knew then? I think we'd have been hard-pressed to do better.

As a fan of the arts, you'll find my movie opinions on Letterboxd.[fn:1] I like bold stuff. The unapologetic and
hard-to-swallow. Big ideas. Meta-commentary. That sort of thing.
** Whatcha Make?
[[file:lists/10-programming-projects.org][Here's a list of some of the big(ish) hobby programming projects I've done, alongside my post-mortem thoughts on them.]]
* Sub-Indices
I've divided this site up into sections, based on "article kind". See those sub-index for lists of what I've written:

- [[file:essays/index.org][Essays]] :: Various long-form opinions on various topics.
- [[file:lists/index.org][Lists]] :: Lists of various kinds, mix of fact and opinion, all entries otherwise too short for something more
  dedicated.
- [[file:guides/index.org][Guides]] :: Non-opinionated guides for how do things that /I/ myself couldn't find any information on. (I'm not going to
  waste your time with "how to install a C compiler" or "how to log in to YouTube".)
* Footnotes
[fn:1] https://letterboxd.com/metroidipc/

[fn:2] I've only actually read G.E.B. though...
