#+SETUPFILE: ../common/common.org
{{{extra_config}}}
#+TITLE: Taking Sides!
#+SUBTITLE: Opinions On Some Trivial Debates
#+OPTIONS: toc:2

* General-Topic

** Systems of Measurement

*** 12-Hour Time or 24-Hour Time?
When I wake up from a nap, I want as little ambiguity possible about whether it's the afternoon or next morning. 24 hour
time!

*** Best Date Format?
ISO 8601 is basically the only one that has a property the others don't: it makes lexicographic ordering and temporal
ordering the same. If you need to standardize on something, then, it only makes sense to standardize on the one that's
strictly more useful.

Relatedly, I'm a fan of the so-called "Holocene calendar" or "human era calendar". Just take the current year, prefix a
'1', and that gives you roughly (around 300 years off) the number of years since the start of the Holocene, /without/
sacrificing your ability to easily parse out the current Gregorian year. I think that's a nice little reminder of the
dizzying depth of human history. (Or perhaps from a geologic perspective, its dizzying shallowness. Only ten thousand
years?)

So: wherever I need a time format string, I pick ~1%Y-%m-%d %H:%M:%S.%N~ (or ~1%Y-%m-%dT%H:%M:%S.%N~) -- just lop off
any precision you don't need.

*** Fahrenheit Vs. Celsius?
I am not a bowl of water. I am also not a 17th century thermometer-maker. A scale that is easy to calibrate with
pre-industrial tools is not per se any more relevant to me than a scale which is /difficult/ to calibrate with those
same tools.

For anthropocentric purposes, "the temperature at which water boils" is probably the /least/ useful point to make an
easy-to-remember round number. I already /know/ what temperature water boils at, because I can look at the pot and /see
it boiling or not./ If it is boiling, then it's at the temperature where water boils. If it isn't boiling, then it's
less than that. Are there really that many other circumstances where I need to know if something is /exactly/ 212
degrees?

100° should be something useful, but difficult to measure without a thermometer. For anthropocentric purposes, anyway.

(For "doing math with temperatures" purposes, neither Fahrenheit nor Celsius are the right tool. Absolute zero is a
clearly more universal constant to fix your zero point to.)

*** Daylight Savings Time Vs. Standard Time?
People prefer to structure their lives around observable phenomena. (This much should be self-evident to anyone who was
doing anything, for any reason, in mid-2020.) In particular, people prefer to be awake -- or at least to do their work
-- when the sun is up. Do we all agree on this? I think we all agree on this.

I think it's ridiculous to try to force people's schedules through something so indirect as /timezones./ It's like if
NHTSA tried to improve driving habits by requiring all speedometers to read 10 km/h faster than actual whenever you were
on the highway. You can just /wake up earlier!/ Most of the professions where alignment with sunlight hours really
matters (e.g. farming) already do this because it's /obvious./ People can regulate their schedules without a shove from
the heavy hand of Congress.

-----

Permanent DST is a particularly stupid solution to this problem. If the whole country wanted to wake up an hour earlier,
they would /do that already./ Why do you think we settled on 9-5 and not 8-4? It's not the time zone. Do you think that
everyone in China wakes up at the same time just because their clocks all say "6:00 AM" at the same time? You can't pray
the circadian cycle away.

I guarantee you that we'd all just shift back to 10-6 (indicated), and then the fact that our clocks are misaligned with
our neighbors would just end up being a stupid bit of trivia.

** Food

*** Pineapple on Pizza?
Delicious.

*** Coke or Pepsi?
Pepsi. The regular, high-fructose corn syrup kind. Never really liked aspertame. Real sugar would be better, obviously,
but I don't care enough to pay the upcharge.

*** Are Brussels Sprouts Good?
Today's are! Can't speak for the older cultivars.

** Language

*** How Many Spaces After a Period?
One. Unless you're fighting for page count. We can type with proportional fonts now, Grandpa. =:P=

*** Oxford Comma?
The utility should be obvious to anyone who's ever read one of those stupid lawsuits where its absence created a legal
loophole.

*** Order of Punctuation with Quotation Marks?
#+begin_aside
See: the "Order of punctuation" section of the Wikipedia "Quotation marks in English" article:
[[https://en.wikipedia.org/wiki/Quotation_marks_in_English#Order_of_punctuation]]
#+end_aside

British/logical style; punctuation not part of the original quote goes outside the quotation marks. Wikipedia uses it,
and that's good enough for me -- it's just less ambiguous.

*** /​ɡɪf​/ Or /​d͡ʒɪf​/?

*​groan​*

I don't care how you pronounce it, so long as you don't try to take the line with me that it's "graphics, not
/jraphics/!" Do you also pronounce "LASER" /​læsɪɹ​/? "CONCACAF" /​kʌnsəkəf​/? "DARPA" /​dəɹpeɪ​/? "SONAR" /​sanæɹ​/?

Of course not. Initialisms are not simply pronounced by concatenating the initial phoneme of each constituent element,
stupid. /They're words./

** Other

*** Should You Rinse Dishes Before the Dishwasher?
The /dishwasher/ rinses your dishes before the dishwasher. *That's what pre-wash means.*

It's also why you should use pre-wash detergent. See:

#+begin_center
[[yt:jHP942Livy0][YouTube Video: Your dishwasher is better than you think (tips, tricks, and how they work)]]
#+end_center

*** Is the Ship of Theseus Still the Same Ship?
Are we still calling it the Ship of Theseus? The /name/ remains. The history remains. The people's relationship to the
symbol remains. It's still as much the same the ship as /anything/ ever could be what it used to be.

* Technical

** Paradigms

*** Functional Vs. Oop?
1. Something something "true OOP has never been tried" something something "actually, I think you'll find it works
   really well in Smalltalk/Objective C before it got bad/my custom fork of the Common Lisp interpreter/some other
   language that, conspicuously, nobody is using to ship real software anymore."

   Perhaps, among all the many, many languages that call themselves "object-oriented", there is an example that makes
   writing good software easy and bad software hard. Myself? I have not found such a language. The state of those that
   followed /Java's/ lead is particularly dire...[fn:1]

   Why must we /only/ encapsulate on object boundaries? Why must we eschew structuring programs as "collections of
   things to do" for "collections of things we can do stuff /to/"? Does that not read as inside-out to people?

2. "Pure functions" are a very elegant idea, on this I agree. I am /less/ sold on the universality of first-order
   functions. Perhaps it only really shines when you get strict about your principles? I admit, most of my experience
   with FP has been in multiparadigm languages. Lisp, Rust, etc.

What I really want out of a language is first-class recognition that subprograms are heterogeneous. Some are pure,
others stateful; some are ~sync~, some are ~async~; some run on servers, some run on clients; some parts on run CPUs,
others on GPUs, or NPUs, or DSPs; some require SIMD, others MIMD; some run natively, others in browsers, others
sandboxed, or in bytecode VMs; they interact with hierarchical caches; they interact with branch prediction; they talk
to each other, they talk to themselves; and so on, and so on.

I would like a language which recognizes this, and makes it easy to /tell the compiler/ what behavior it should expect
of a variable, or a subprogram, or system resource. Not simply the things that it /does,/ but equally importantly the
things it /doesn't/ do. We might then modularize our software on boundaries of shared effects and capabilities, each
sub-module further constraining the possibility space until it is trivial to reason about.

The more we can reason, the more powerful the metaprogramming we can provide. Each bottom-level module can settle into
its own pseudo-DSL, describing behavior /as befits its nature./ "I am a collection of pure arithmetic functions on
floats, here are some equations, please convert them to optimal SIMD", "I am a description of a protocol, here is my
specification, prove its soundness and provide implementations of the things it describes", "I am a set of tasks, here
is they require, what they do, and what they provide, please construct the backing parallel runtime and data structures
to run them in", "I am a UI, here are my elements and their relationships, please construct an event loop to run them
and the means to update my state" and so on and so forth.

Wouldn't that be wonderful? To be able to /imply/ parallelization, or IPC, or fronted-backend, or coprocessor offload,
all with just type signatures? At least for trivial cases?

I understand that there are optimizations compilers will never intuit. A /lot/ of optimizations they'll never intuit. I
hope that, for those cases, this approach would still make it easier to write programs than it would make them harder.

I suspect the answer lies somewhere between LISP, Ada, CUDA, Julia, perhaps OpenMP, functional programming; but I
confess I'm too uninformed to say anything definitive. Call me back when I'm more experienced?

*** Dynamic Vs. Static Typing?
"Check it out guys: we managed to save a whole year building this new airliner by never checking if we bought the right
materials!"

I can accept dynamic typing for projects with less than a hundred SLOC. Two hundred is a perhaps, three hundred is
really pushing it, and four hundred is /way/ too big to reason about. You're gonna start making type errors.

If your language has types, I don't understand why you would want to wait as /long as possible/ to tell me I've used
them wrong. You aren't saving me from errors, the error was there to begin with! The language knew that, I didn't; why
hide that?

*** Strong Vs. Weak Typing?
"Check it out guys: we managed to save a whole year building this new airliner by re-using all these old washing machine
bolts! The thread pitches are different, but we just cranked 'em down anyways! They're almost flush, even!"

Weak typing does not reduce program complexity, it just makes it harder to understand the complexity that was already
there. I do not /want/ to add a integer to a string. That is not a well-formed operation. I cannot predict its behavior.
I can /guess,/ but I'll never know for sure, unless I read the standard.

Moreover, when I /do/ read the standard and find therein that ~String + Integer~ actually means "convert this integer to
a string with ~.toString()~ and then ~.join()~ them", then at that point what benefit does this ambiguous ~+~ operator
actually give me over an explicit ~String.join(Integer.toString())~? Golf cred? Screw golf cred. I want to write what I
/mean./

*** Is C Really "Low-Level"?
No,[fn:2] and I think that's holding us back. I shouldn't have to know how to coerce the compiler into producing the
right assembly, I should be able to just /say/ what I expect. Modern ISAs are shockingly expressive, why shouldn't we
let users take advantage of that?

** Hardware

*** AMD Vs. Intel?
Intel are an amusing company. Their in-house architectures all suck, their CPUs implementing those architectures suck,
their CPUs implementing other people's architectures suck, their attempts to innovate always crash and burn, and somehow
they're /still/ number 1. How does that even happen?

I'd like to see one of their wacky ideas finally pay off one day. 'Til then? Yeah, you should probably just buy AMD...

*** RISC Vs. CISC?
Any architecture that gives more avenues for static optimization gets my vote. RISC, VLIW -- NISC, even -- I find these
very appealing.

Unfortunately, nobody is really making any new "the ISA /is/ the metal" processors these days. It's all compromised. Did
you know that ARM has a instruction just for JavaScript? ~FJCVTZS~, AKA "Floating-point Javascript convert to signed
fixed-point, rounding toward zero".[fn:3]

I don't see the point comparing architectures when the only distinguishing factor is how long or short their microcode
listings are. Use whatever gives you the better numbers.

** Ideology

*** LLMs and "Vibe Coding"?
The most important fact to internalize about large language models is that they're /profoundly/ stupid. They will lie,
they will overstate, they will misunderstand, and they will be biased. There is no question you can ask that will never
get a wrong answer. Never do anything with an LLM's "opinion" that does not *centralize* this fact.

The second most important fact to internalize is: they cannot tell you if they're /actually/ confident, or are just
answering /as if/ they were confident. On some level they're the same thing. What's the last time you asked ChatGPT a
question and replied by asking for /your/ help? Has it *ever* happened? There's simply no possible way to know if an LLM
has a real understanding of a problem if you don't have that yourself. Never make a decision on the basis of an LLM's
input without considering this too.

Evangelists may attempt to convince you that the solutions to these problems are only a matter of time.

I disagree.

There's only one real way to get value (and I mean 'value' here as coldly and pragmatically as possible) out of
something that is architecturally incapable of meta-cognition:

1. *Only ever bet your time.* If a wrong answer will cost you more than an hour of frustration, reevaluate.
2. *Stay transactional.* This isn't a conversation, /you are trying to take advantage of The Man's several billion
   ill-spent dollars./
3. *Keep conversations as short as possible* and *delete them as often as possible,* to serve points 1 and 2. If you
   want a permanent record of what you've learned, take notes somewhere else.

If you can't keep to those rules, try reconsidering what it is you're trying to do. Break the problem down into smaller
parts, where the answers are easy to verify. "How do I make Flappy Bird in Objective-C" will only end badly, "how do I
compile Objective-C with ~gcc~" will either be right, or it'll breadcrumb you to the right answer anyway, or at /worst/
will just fail really obviously.

Don't be afraid to lead it on, too. If you can't figure out what library you need to use to draw a 3D graph in python,
ask it to write a python program that draws a 3D graph, but don't copy-paste the code. We're here for facts. Facts like
"what libraries is it using" or "how is it structuring these API calls" or "what does it mention in its docstrings".

Once you're done, write down what you've learned -- or at least take a mental note of what's happened -- then delete the
conversation and go again. The less it knows about what you're doing, the more general its responses will be; and the
more general its responses are, the easier it will be verify them.

Eventually, you'll have a solution /and/ an understanding of the problem. That's what really matters.

*** UNIX Philosophy?
Despite what I might have implied earlier, I don't really care about the UNIX philosophy.

It's a decent set of principles for writing coreutils, but quickly grow inane when you try to apply them to anything
real. What even is "a program"? I've never seen a good answer from the diehards that doesn't contradict what they seem
to believe in practice.

Look closer, and you'll find that most applications /are, in fact,/ collections of smaller programs that all do one
thing well.

#+begin_example
$ pacman -Ql systemd systemd-resolvconf systemd-sysvcompat netctl \
  | awk '$2 ~ /^(\/usr)?\/bin.*[^/]$/ { counter++ } END { print counter }'
68
#+end_example

Who could have guessed: just because /you/ don't know how to hack on something, doesn't mean "Q.E.D. it's a monolith".

-----

Also: not everything is a file. Your pants are down, and your embarrassing ~ioctl~-themed underwear is showing. See:

#+begin_center
[[yt:9-IWMbJXoLM][YouTube video: "What UNIX Cost Us" - Benno Rice (LCA 2020)]]
#+end_center

*** GPL Vs. MIT?
FOSS is dead. Open source is dead. Free software is dead.[fn:4]

When I /do/ want a license, I like MPL v2.0.

See: [[https://choosealicense.com/licenses/mpl-2.0/]] for the high level, [[https://www.mozilla.org/en-US/MPL/2.0/]] for
the nicely-formatted text, and [[https://www.mozilla.org/en-US/MPL/2.0/FAQ/]] for some of the nitty-gritty.

** Formatting

*** Tabs vs. Spaces?
Doesn't matter. Manual indentation is for monkeys on typewriters. As long as you, the maintainer, are willing to put in
five minutes to enforce your norms with an ~.editorconfig~,[fn:5] I'll use whatever you want. Otherwise, ~M-x tabify~,
~M-x untabify~, and ~M-x indent-according-to-mode~ are my friends.

*** Significant Whitespace?
Significant whitespace is for idiots who /wish/ they were monkeys on typewriters. I don't trust a language that
incentivizes 1.) never writing an expression longer than my fill-column minus the current indentation level or 2.)
looking like Bourne Shell. Worse, it makes tabs vs. space a real nightmare. XML, god bless them, had at least this
right: program structure should only ever be determined by the things you can /see./ Never the things you /can't/ see.

*** Brace Style?
Open brace on the same line for blocks where the declaration is a single line, next line /iff/ the declaration contains
information that should itself be indented. (i.e. ~where~ clauses, ~throws~ clauses, other information that goes beyond
return type, accessor flags, name, arguments) Braces are indented to the level above their comments (Whitesmiths-style
makes my head hurt.)

#+begin_src C
  int main(int argc, char* argv[]) {
      // do stuff...
  }
#+end_src

#+begin_src rust
  pub fn flow_inner_wrapper<I, T>(task_context: &TaskContext, tasks: I) -> Result<()>
  where
      I: IntoIterator<Item = (&'static str, T)>,
      T: FnOnce(&TaskContext) -> Result<()>,
  {
      // do stuff...
  }
#+end_src

#+begin_src java
  @Override
  public void onLoad(ClassPool pool, String classname)
          throws NotFoundException, CannotCompileException
  {
      // do stuff...
  }
#+end_src

But in general I'd rather delegate to external tooling than make the decision myself. Configure a formatter hook in your
flow orchestration! Or at least make a common configuration for your team's LSP.

*** In C: ~int *foo;~ or ~int* foo;~?
The latter. I understand the argument for the former, I /know/ that declaring multiple variables on a single line like
e.g. ~int* i, j;~ means ~i~ is an ~int~ /pointer/ and ~j~ is an ~int~ /value/ -- I contend that this was a mistake on
Dennis Ritchie and ANSI and ISO's parts. The type is ~(int*)~! Perhaps it was an attempt to make source code take up
less disk space, like SGML omissible end tags? It's still an antiquated mechanism if so.

I get around the problem by just never declaring multiple variables on the same line.

** Other

*** Editor War?
#+begin_center
[[yt:V3QF1uAvbkU][YouTube video: Emacs or VI: The Definitive Answer.]]
#+end_center

Emacs forever! ~(while (and (rules 'emacs) (drools 'vi)) (message "you already know it"))~

Vi -- and its issue -- are *text editors.* They do many things, and they do not do all of them well. They open files,
they insert text into files, they change text in files, they launch subcommands, they run shells, they multiplex, they
do IPC, they gesture at extensibility. All in just one program. (Not what you were expecting me to say?)

Emacs is an *environment.* It is a guest VM with host filesystem access (and remote filesystem access) and ten thousand
preinstalled utilities for text manipulation. ~search-forward-regexp~, ~magit-status~, ~default-indent-new-line~,
~eshell~, ~eww~ -- these are not commands.[fn:6] They're single purpose, well-made, filtering, plain text-acting,
inter-operating /programs./ You can even go look up their source code, whenever you want! ~M-x find-function RET
foo-bar RET~.[fn:7]

Who's the real UNIX philosophy exemplar here? ~ed~ with bolt-ons? Or the purpose-built, hackable, extensible, cohesive
software distribution?

You can even use Elisp programs in your shell scripts! (With pipes!) Some trivial examples:

#+begin_example
$ emacs --batch --eval="(pp (car '(:foo :bar)))"
:foo
$ seq 10 | emacs --batch --eval='(with-temp-buffer
                                   (insert-file-contents "/dev/stdin")
                                   (while (re-search-forward "[123]" nil t)
                                     (replace-match "W"))
                                   (princ (buffer-string)))'
W
W
4
5
6
7
8
9
W0
$ emacs --batch \
      --load=~/.emacs \
      --file=index.org \
      --funcall=hack-dir-local-variables-non-file-buffer \
      --funcall=org-publish-current-project
Loading /home/fooUser/metroidisprettycool.github.io/.emacs/yt-embed.el (source)...
Created yt link.
Loading /home/fooUser/.org-timestamps/metroidisprettycool.github.io.cache...
Publishing file /home/fooUser/metroidisprettycool.github.io/src/lists/00-taking-sides.org using ‘org-html-publish-to-html’
Skipping unmodified file /home/fooUser/metroidisprettycool.github.io/src/essays/00-more-right.org
Publishing file /home/fooUser/metroidisprettycool.github.io/src/essays/10-java.org using ‘org-html-publish-to-html’
Publishing file /home/fooUser/metroidisprettycool.github.io/src/index.org using ‘org-html-publish-to-html’
#+end_example

I admit it's less /flexible/ when you yank it out into shell-land like this, but why /should/ it be flexible? The
ecosystem is the /point/ of the ecosystem. The interactivity is the /point/ of the interactivity.

If I find I have a real need to move some data around between Emacs and a shell program, I've got so many more options
from /within/ than I do without:

1. There's the inferior shell, invoked with the command ~M-x shell~;
2. and the Eshell, invoked with the command ~M-x eshell~;
3. and inferior terminal mode, AKA ~term-mode~, invoked with the commands ~M-x term~ or ~M-x ansi-term~ (depending on
   what /exactly/ you want, behavior-wise).
4. Then there's the command ~shell-command~, invoked with ~M-!~ or ~M-x shell-command~, /or/ with a prefix argument
   (~C-u M-!~, ~C-u M-x shell-command~) to insert output into the current buffer, /or/ called directly from lisp via
   ~M-: (shell-command COMMAND &optional OUTPUT-BUFFER ERROR-BUFFER) RET~;
5. and the command ~shell-command-on-region~, invoked with ~M-|~ or ~M-x shell-command-on-region~, /or/ with a
   prefix argument (~C-u M-|~, ~C-u M-x shell-command-on-region~) to /replace/ the given region with the results.
6. There's the command ~dired-do-shell-command~, bound by default to ~!~ in ~dired-mode~ and /also/ invocable with ~M-x
   dired-do-shell-command~.
7. There's the lisp function ~(make-process)~, invocable interactively with ~M-: (make-process &rest ARGS)~;
8. and the lisp function ~(call-process)~, invocable interactively with ~M-: (call-process PROGRAM &optional INFILE
   DESTINATION DISPLAY &rest ARGS)~;
9. and the lisp function ~(call-process-region)~, invocable interactively with ~M-: (call-process-region START END
   PROGRAM &optional DELETE BUFFER DISPLAY &rest ARGS)~.
10. and like three or for more I don't remember the details of.
11. Oh, and like a billion external packages from GNU, NonGNU, MELPA, etc.

And guess what? Commands are merely a specially-marked kind of lisp function, so they're also usable anywhere a
non-command lisp function would be, such as being invoked explicitly via ~M-:~, from within Elisp scripts, and from
within other functions. All are customizable and hackable and extensible and re-usable and /documented./

Everything in Emacs is documented! Want the help page for the function ~foobar~? ~C-h f foobar~, and as a bonus you get
whatever key bindings will invoke it (if any). Want the help page for the variable ~foobar~? ~C-h v foobar~. Want both?
(Elisp is a Lisp-2.) ~C-h o foobar~. Not sure what exactly you're looking for? Try ~C-h a~ to do an apropos search. Want
to search for something in the Emacs ~info~ manual? ~C-h r~ for ~info-emacs-manual~, then ~s~ in the ~info~ window for
~Info-search~, then just type what you're searching for. Repeat the search until you find it. What about the Elisp
~info~ manual? ~C-h R elisp~ for ~info-display-manual~, then ~s~ and the thing you're searching for like before. Want a
specific ~info~ top-level manual, like, for example, the eshell manual? ~C-h R eshell~. Not sure what ~info~ manuals are
installed? ~C-h i~. Need a man page instead? ~M-x man~. Not sure what keybindings are available in a given major-mode?
~C-h m~ lists the major mode of a window, and all the minor modes, and all their key bindings. Want to know what
function a key binding runs? ~C-h k~, and then type the key binding, e.g. ~C-h k C-x C-f~ opens the help page for
~find-file~. It even works for mouse bindings, too!

I could go on and on. What do Bash and Vi and tmux and a thousand little ncurses programs -- all of which are still
complexity you'll have to learn, I might add -- give me that Emacs doesn't? Worse scripting languages? "Job control"?

No thanks.

* Art and Media

** Philosophy

*** Is 'Stupid Modern Art' (e.g. /Comedian/ [2019] by Maurizio Cattelan) Really Art?
A Thing is Art if it's having a conversation with Art.

** Specific Works

*** Garfield or Heathcliff?
Heathcliff and it's not even close. It's not even comparable. Garfield is nothing. He's a vacuum. An empty wrapper. An
egg with no yolk. A shadow on the wall. The snake eating its tail eating its tail eating its tail eating its tail eating
its tail eating its tail eating its tail. Around and around and around forever.

Heathcliff, on the other hand, is /funny./

Or at least interesting. You just gotta... marinade it in a for a little while. Maybe check out this interview with
Peter Gallagher:

https://solrad.co/let-the-art-stand-for-itself-a-conversation-with-peter-gallagher

or this talk that he did:

#+begin_center
[[yt:o8_8En04p08][YouTube video: CXC 2022: Heathcliff is Having a Moment with Peter Gallagher]]
#+end_center

*** So, like, What Is /Evangelion/ Even About?
A lot of things. Human relationships. Losing. Winning. Growing up in a world too traumatized to look you in the eye.
Child soldiers. Playing the cello. Sexuality. Greed. Suicide.

Broadly, though? /Evangelion/ is about how when you don't understand yourself or the world around you, everything you
touch starts to die. Uh-oh!

*** Are the Star Wars Prequels / Sequels / Originals Actually Good?
Possession of a legal right to continue a work does not confer the ability to say anything interesting about that work.
Franchises are not /real./

I don't give a damn about any of the shows besides Tartakovsky's /Clone Wars/, so here's just my thoughts on every
movie, in in-universe chronological order:

- TPM :: The best production design we see outside the OT, coupled with a plot that's a lot of boring dicking around in
  a desert. Racist and boring and clumsy. Still, could be worse.

- AotC :: Unwatchable nonsense. There are maybe two interesting plot threads here, and in a perfect world they would've
  been merged into /TPM/ to make room for the clone wars on the big screen. Oops.

- SW:TCW :: Uuuuuhghghhhhh. You can tell that this is a bunch of first season /TCW/ episodes edited together. Dave just
  Filoni'ed all over them. Can I please watch the 2003 /Clone Wars/ instead?

- RotS :: Fatally clumsy, but in its broadest strokes my favorite prequel. I like the conversations, but not much of the
  dialogue. I like the fights, but not the choreography. I like the locations, but not the sets (using that term very
  loosely.) This is the /Star Wars/ film I most want to read a novelization of.

- S:ASWS :: Decent production design, decent performances, braindead concept. The L&M take /could have/ elevated this,
  but my instincts tell me it'd probably still just be ehhhh but in a different way. There's a quality ceiling imparted
  by the whole "Han Solo origin story" thing. I'd have preferred they just made a different movie about different
  characters doing different things at a different time.

- RO:ASWS :: Can you tell this film spent more time as concept art than as a script? Like /ANH/, I enjoy the production
  design too much to really hate this film, weak performances notwithstanding, but it /is/ a pretty weak film.

- ANH :: This film has a lot of charismatic characters but not a lot of /interesting/ characters. Joseph Campbell's
  poison pill has already entered the bloodstream. Still, the production design is too much of a winner to make this a
  /bad/ movie.

- SWHS :: Demented cinema verite variety show Wookie bullshit. Feels like eight hours. That's so brazen it's almost
  respectable, but for all its cult status, it's /still/ not worth watching. Really, honestly: *don't bother.* Don't
  watch it. If you and your friends get together to watch it for some reason, spend the whole time on your phone or
  knitting or doing a puzzle so you don't have to actually take it in.

- TESB :: The good one!

- RotJ :: The lack of strong character writing is catching up to us. The interesting ideas here are mostly retreads, and
  the /uninteresting/ ideas dominate. I'd have liked to see the better bits of this movie moved backwards to ANH and
  TESB or vice-versa. As is, this just feels like padding. It might be tolerable in a middle installment, but this is a
  finale! That's no good.

- CoC:AEA :: TODO!

- E:TBfE :: TODO!

- TFA :: A coward's movie, which introduces essentially nothing to the franchise but a new cast of charismatic
  non-characters. Is this a commentary on the cyclical nature of war, or just a depiction of the same. (The latter.)
  Only Kylo Ren is set up for an arc, but watching him is like putting on a pair of wet socks. I'm so tired of padding.

- TLJ :: After the non-start of /TFA/, /TLJ/ stumbles hard trying to play catch up in some characteristically Rian
  Johnson ways. Still more interesting than its successor or antecessor though.

- TRoS :: Rushed, rude, compromised, and just an avalanche of nonsense. I like some of it -- as abstract ideas, at least
  -- but the sum total feels like a film that's annoyed it even has to try. I'm so tired. I just want /Star Wars/ to
  give up and die already. I guess at least it's a consolation that Colin Trevorrow didn't write it...

** Medium

*** Foreign Language Audio: Dubbing or Subtitles?
Subtitles are usually the way to go, for all the obvious reasons.

On a re-watch/re-listen of a work you really like, though, it can be interesting to check out the dub just to see how
they reinterpreted it. I do that occasionally.

*** Physical Vs. Streaming?

**** Music
I do most of my music listening on YouTube Music w/ adblocker, 'cause I'm lazy. Lately, though, I've been trying to
build up a CD collection. Good sound that works natively with my computer /and/ it's a physical thing? Sign me up!

**** Movies
I can watch my $2 thrift store DVDs whenever I want, /and/ they have deleted scenes + BTS content + directors
commentary. Even most piracy sites only bother dealing in the movies themselves. I want historical context!

*** Is Adblock Piracy?
Probably! But that's not a value judgment.

* Space and Spaceflight

** Astronomy

*** Is Pluto Still a Planet?
All models are wrong, but some are irrationally defended by people who wish they were still in the third grade -- when
"knowing what a rhombus is" was enough to coast through life unalloyed.

2006 was actually the /second/ time we reclassified some former planets, did you know that? That's "planets" plural; in
1867 1 Ceres, 2 Pallas, 3 Juno, 4 Vesta, 5 Astraea, 6 Hebe and 7 Iris all got reclassified as asteroids (Ceres had been
a planet for over 65 years at that point!) and in 2006 134340 Pluto, 136199 Eris, and -- guess what -- 1 Ceres all got
reclassified as dwarf planets. (And there are some other cases of things being called planets for a year or two before
getting reclassified, see: [[https://en.wikipedia.org/wiki/List_of_former_planets]])

#+begin_aside
Ceres is /obviously/ the best dwarf planet, because it's literally number one!
#+end_aside

Not a lot of people arguing that /Vesta/ should be a planet again, right? I mean, maybe they /should,/ but what I mean
is that if the argument for Pluto was tradition, you'd think the proponents would be a little choosy with that
tradition...

I don't care how many axes you can drum up that frame things as "rocky planets vs. gas giants" or "it's about
hydrostatic equilibrium" or whatever contrived examples you want to come up with. Yes, there are ways that Pluto is more
like some of the eight planets than those planets are like each other. Guess what? There are things to study in
astronomy besides mineral geology. The IAU definition of "planet" is more useful in more ways than other definitions. We
checked! That was the whole point of making a formal decision! So you aren't gonna get anywhere with whining. Besides
peeving me, anyway.

** Spaceflight History

*** Space Shuttle Vs. Buran (or) Energia?
It's easy to argue that Energia-Buran was more capable when it never had to demonstrate any of those proposed
capabilities.

It's a bit... /meandering,/ but see this video:

#+begin_center
[[yt:ytmFLbPh7ss][YouTube video: The Buran is Overrated]]
#+end_center

I also take issue with the position that accepts Buran's failings but argues for Energia as a standalone heavy launcher.
It smacks of apologetics to me. Spacecraft and launch vehicle efficacy is determined by more than just the easy numbers
-- I_sp, cost of propellants, time to prep for launch, etc. It's very telling that /Polyus/ had to be mounted with its
engine upside-down to mate with Energia 6SL. Does this strike confidence in Energia as a general-purpose launch vehicle?
That it had such specific requirements for payloads that they might have to be mounted upside-down? That those payloads
might have to do a /backflip/ to reach orbit?

STS sucked and killed a lot of people. But I don't think any other program could have delivered as much as it did, with
that budget. Could a next-gen capsule have given us the Hubble Space Telescope? The ISS International Segment? Spacelab?
Spacehab? The Long-Duration Exposure Facility? The Solar Maximum Mission rescue? The Wake Shield Facility? EURECA?
ATLAS-1 or SEPAC?

I don't think so.

*** Who Won the Space Race?
It's easy to paint the USSR as an unambiguous winner if we just look at the "first to X milestone" numbers. I'm sure
we've all seen that meme that goes something like "first satellite in space, first animal in space, first man in space,
first woman in space, first space walk, first space station -- USSR. First man on the moon, USA. Winner? USA!?"

Well, here's something to note: Between April 12th, 1961 (first human spaceflight) and December 26th, 1991 (collapse of
the USSR) the USSR flew 2 women on 3 person-flights,[fn:8] out of 94 flying cosmonauts and 142 person-flights.[fn:9] If
we include /Interkosmos/ cosmonauts, these numbers rise to 3 women, on 4 person-flights, out of 101 flying cosmonauts
and 150 person-flights.

In that same time, the USA flew 13 women on 19 person-flights,[fn:10] out of 154 flying astronauts and 285
person-flights.[fn:11] If we include payload specialists (whose selection is (was?) more complicated than traditional
astronauts) these numbers rise to 15 women on 22 person-flights, out of 154 astronauts and 312 person-missions.

Now, 13 is obviously not half of 285. Even if we restrict ourselves just to the Space Shuttle program, 13 is still not
half of 201. /Obviously/ inequitable. But 6.7% is a hell of a lot bigger than 2.1%.

Today the disparity is even wider -- 20 women and 28 men are active members of the NASA astronaut corps, 1 woman and 22
men are active members of the Roscosmos cosmonaut corps. Only four Russian women have flown to space since 1991, three
cosmonauts and an actress. (Not actress-turned-cosmonaut, just actress. She went to the International Space Station to
film a movie for state-owned TV broadcaster Channel One Russia.) The US has put up another fifty or so. (exact figure
depends on how you want to consider private spaceflights, payload specialists, space tourists, etc.) No Russian woman
has flown more than once since Yelena Kondakova in 1997, who flew twice. No Russian or Soviet woman has flown more than
twice.

There are more American women who have flown to space /exactly four times,/ than there are Russian women who have flown
/ever./ No Russian woman has ever commanded the ISS, or, for that matter, any mission. (Arguably the Soviets had one,
Valentina Tereshkova "commanded" her single-occupant Vostok 6; but given the technical nature of the Vostok capsule, and
the fact her flight was shorter than the three flight preceding her, I'm more inclined to say she was treated closer to
a human life sciences payload.)

The Soviet Union flew the first woman into space because they heard the US might be doing the same (misconstruing the
Mercury 13), and they wanted to be first. Then, they didn't fly a single woman for another twenty years. None of the
other four candidates would ever fly. Then the Soviet Union did the first female spacewalk, because they heard the U.S.
was going to be doing the same, and they wanted to first. No Soviet or Russian woman has conducted a spacewalk since.

Here's another bit of trivia you might not know: from 1963 to 1975, the USSR made 7 successful robotic landings on the
Moon, including the very first with Luna 9 in 1966. If we also consider 1976 -- the last year of first-gen lunar
landings and only a year beyond our 1975 ASTP cutoff date -- that's 8 landings.

8 landings out of *27 attempts*, that is.

In the same time-frame, the US made five robotic landings and six manned landings -- out of seven and seven attempts,
respectively.

This sort of parallels the respective Venus programs of both countries a couple years later. The Soviet Union made nine
landings on Venus, out of twelve attempts; the US made one landing on Venus out of *no* attempts. Did you know that?
Hughes overbuilt the Day probe (intended only for atmospheric data collection) so much that when it hit the ground
/without a parachute,/ it just kept transmitting! For over an hour! (The Night probe, part of the same mission, /also/
survived impact, but only for two seconds. Still a laudable accomplishment, but not really a "successful landing" in my
book.)

Here's a third piece of trivia: while the USSR did get the first ever EVA ("spacewalk"), it's the US that got the second
and third. And fourth. And fifth. And sixth and seventh. Also eight, ninth, and tenth. Then the USSR got the eleventh,
and the US got the twelfth. And thirteenth, fourteenth, fifteenth, sixteenth, seventeenth, eighteenth, nineteenth,
twentieth, and twenty-first (though you might not count those, because they didn't happen in Zero G. Walking on the Moon
is cheating!) then the twenty-second EVA in deep space, before another six moonwalks and two more deep-spacewalks. Oh,
and also the thirty-first, thirty-second, thirty-third, thirty-fourth, thirty-fifth, thirty-sixth, thirty-seventh,
thirty-eighth, thirty-ninth, and fortieth on Skylab.

Then we hit Apollo-Soyuz, and the space race is officially over!

Isn't it a little ridiculous to claim a milestone is yours when you could barely replicate it? EVAs are only valuable
when you have a facility that requires them -- usually either a station, or a surface ops site. The USSR did not develop
such facilities or mission profiles before the US did. Period.

I am aware that, unlike the number of women flown in space, this statistic evens out a bit after 1975, as both nations
entered their respective 80s forever programs -- STS, and second and third generation DOS space stations. The USSR would
make 41 spacewalks from 1975-1991, the US only 15. This brings totals up to 43 and 55, respectively. Things would swing
back the other way going into the ISS, but at that point the USSR was no more and things get even more geopolitically
complicated.

* {{{license_footer(2025)}}}

* Footnotes

[fn:1] [[file:../essays/10-java.org]]

[fn:2] [[https://queue.acm.org/detail.cfm?id=3212479]]

[fn:3] [[https://developer.arm.com/documentation/ddi0602/2025-09/SIMD-FP-Instructions/FJCVTZS--Floating-point-Javascript-convert-to-signed-fixed-point--rounding-toward-zero-]]

[fn:4] [[https://www.boringcactus.com/2020/08/13/post-open-source.html]]

[fn:5] [[https://editorconfig.org/]]

[fn:6] I mean, they /are/ commands, because they have ~(interactive)~ declarations, but what I mean is that they aren't
built-ins. The thing you're commanding isn't /Emacs./ It's whatever package declared that function.

[fn:7] Stuff that's in C source code (like ~car~ and ~cdr~ and ~self-insert-command~ and other primitives) require a bit
of extra config, and you need to have the source code available on-disk somewhere. Can still do it, though.

[fn:8] Not including unflown cosmonauts or /Interkosmos/ cosmonauts.

[fn:9] Including Soyuz 1, 11, 7K-T No.39, 7K-ST No.16L, and TM-13; not including unflown cosmonauts or /Interkosmos/
cosmonauts.

[fn:10] Including /Challenger/ STS-51L, not including unflown astronauts or payload specialists.

[fn:11] Including /Challenger/ STS-51L, X-15 flights over 50 miles -- even X-15 flight 191 -- and Apollo 1, and Gemini
6; not including Gemini 9, ALT 1-16, unflown astronauts or payload specialists.
